# -*- coding: utf-8 -*-
"""LatihanSBA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOrXj0NrdJVi2f9TShSbVvHSkeMm1P5s

# Cara simpan
> klik `file` -> `Download .py`
## kemudian upload ke netacad di soal anda.
"""

'''
namafile: latihanSBA.py
Lembar kerja/script Latihan SBA
'''
# >>>>>>LEMBAR KERJA>>>>>>>>>
# lembar ini hanya berisi pendefinisian fungsi dan class saja

#email netacad, JANGAN SAMPAI LUPA >>>>>>><<<<<<<
email = 'bagus.gov.id@gmail.com'

class titik2d:  
  pass
  def __init__(self, x, y):
    self.x = float(x)
    self.y = float(y)

  def ambiltitik(self):
    return (self.x , self.y)

  def tambahkan(self, titik):
    self.x = titik.x + self.x
    self.y = titik.y + self.y
    return (self.x , self.y )


def run():
  pass
  while(True):
    try:
      x, y = input("Enter x and y: ").split()
      break
    except:
      print('Please input two value using space like this: 2 3')

  return titik2d(x,y)


if __name__ == '__main__':
  # >>>>>TEST DI SINI>>>>>>
  # gunakan BLOCK MAIN ini untuk mengetes

  # untuk pengetesan kode hanya boleh di bagian sini
  # silakan test sesuka hati di sini
  t1 = run()
  t2 = run()
  print('titik1:',t1.ambiltitik())
  print('pertambahan t1 dan t2:',t1.tambahkan(t2))
  print('nilai titik t1 setelah ditambahkan:',t1.ambiltitik())

  # >>>>>AKHIR TEST DI SINI>>>>>>
